
// export enum Events_get {
//     LED_GET_ESTADO_TENDEDERO = "LED_GET_ESTADO_TENDEDERO",
//     LED_GET_ESTADO_JARDIN = "LED_GET_ESTADO_JARDIN",
//     LED_GET_ESTADO_TIMBRE = "LED_GET_ESTADO_TIMBRE",
//     LED_GET_ESTADO_TEMPERATURA = "LED_GET_ESTADO_TEMPERATURA",
//     LED_GET_ESTADO_TINACO = "LED_GET_ESTADO_TINACO",
//     LED_GET_ESTADO_NIVEL_BOMBA_AGUA = "LED_GET_ESTADO_AGUA",
// }

// export enum Events_send {
//     LED_SEND_ESTADO_TENDEDERO = "LED_SEND_ESTADO_TENDEDERO",
//     LED_SEND_ESTADO_JARDIN = "LED_SEND_ESTADO_JARDIN",
//     LED_SEND_ESTADO_TIMBRE = "LED_SEND_ESTADO_TIMBRE",
//     LED_SEND_ESTADO_TEMPERATURA = "LED_SEND_ESTADO_TEMPERATURA",
//     LED_SEND_ESTADO_TINACO = "LED_SEND_ESTADO_TINACO",
//     LED_SEND_ESTADO_NIVEL_BOMBA_AGUA = "LED_SEND_ESTADO_NIVEL_BOMBA_AGUA",
// }

// export enum Events_set {
//     LED_SET_ESTADO_TENDEDERO = "LED_SET_ESTADO_TENDEDERO",
//     LED_SET_ESTADO_JARDIN = "LED_SET_ESTADO_JARDIN",
//     LED_SET_ESTADO_TIMBRE = "LED_SET_ESTADO_TIMBRE",
//     LED_SET_ESTADO_TEMPERATURA = "LED_SET_ESTADO_TEMPERATURA",
//     LED_SET_ESTADO_TINACO = "LED_SET_ESTADO_TINACO",
//     LED_SET_ESTADO_NIVEL_BOMBA_AGUA = "LED_SET_ESTADO_NIVEL_BOMBA_AGUA",
// }

export enum Dispositivos {
    PERCIANAS = "PERCIANAS",
    ALARMA = "ALARMA",
    ALARMA_BEBE = "ALARMA_BEBE",
    PUERTA_MASCOTA = "PUERTA_MASCOTA",
    TENDEDERO = "TENDEDERO",
    JARDIN = "JARDIN",
    LUZ = "LUZ",
    ENERGIA = "ENERGIA",
    DISPENSADOR_ALIMENTOS = "DISPENSADOR_ALIMENTOS",
    AGUA = "AGUA",
    TIMBRE = "TIMBRE",
    TEMPERATURA = "TEMPERATURA",
    TINACO = "TINACO",
    CISTERNA = "CISTERNA",
    PUERTA = "PUERTA",
    ESCALERAS = "ESCALERAS",
    REFRIGERADOR = "REFRIGERADOR",
    DETECTOR_HUMO = "DETECTOR_HUMO",
    DETECTOR_GAS = "DETECTOR_GAS",
}

export enum Events_get_mqtt {
    GET_PERCIANAS = "GET_PERCIANAS",
    GET_ALARMA = "GET_ALARMA",
    GET_ALARMA_BEBE = "GET_ALARMA_BEBE",
    GET_PUERTA_MASCOTA = "GET_PUERTA_MASCOTA",
    GET_TENDEDERO = "GET_TENDEDERO",
    GET_JARDIN = "GET_JARDIN",
    GET_LUZ = "GET_LUZ",
    GET_ENERGIA = "GET_ENERGIA",
    GET_DISPENSADOR_ALIMENTOS = "GET_DISPENSADOR_ALIMENTOS",
    GET_AGUA = "GET_AGUA",
    GET_TIMBRE = "GET_TIMBRE",
    GET_TEMPERATURA = "GET_TEMPERATURA",
    GET_TINACO = "GET_TINACO",
    GET_CISTERNA = "GET_CISTERNA",
    GET_PUERTA = "GET_PUERTA",
    GET_ESCALERAS = "GET_ESCALERAS",
    GET_REFRIGERADOR = "GET_REFRIGERADOR",
    GET_DETECTOR_HUMO = "GET_DETECTOR_HUMO",
    GET_DETECTOR_GAS = "GET_DETECTOR_GAS",
}

export enum Events_send_mqtt {
    SEND_PERCIANAS = "SEND_PERCIANAS",
    SEND_ALARMA = "SEND_ALARMA",
    SEND_ALARMA_BEBE = "SEND_ALARMA_BEBE",
    SEND_PUERTA_MASCOTA = "SEND_PUERTA_MASCOTA",
    SEND_TENDEDERO = "SEND_TENDEDERO",
    SEND_JARDIN = "SEND_JARDIN",
    SEND_LUZ = "SEND_LUZ",
    SEND_ENERGIA = "SEND_ENERGIA",
    SEND_DISPENSADOR_ALIMENTOS = "SEND_DISPENSADOR_ALIMENTOS",
    SEND_AGUA = "SEND_AGUA",
    SEND_TIMBRE = "SEND_TIMBRE",
    SEND_TEMPERATURA = "SEND_TEMPERATURA",
    SEND_TINACO = "SEND_TINACO",
    SEND_CISTERNA = "SEND_CISTERNA",
    SEND_PUERTA = "SEND_PUERTA",
    SEND_ESCALERAS = "SEND_ESCALERAS",
    SEND_REFRIGERADOR = "SEND_REFRIGERADOR",
    SEND_DETECTOR_HUMO = "SEND_DETECTOR_HUMO",
    SEND_DETECTOR_GAS = "SEND_DETECTOR_GAS",
}